name: ADF_NEW_2

on: 
  workflow_dispatch

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_RESOURCE_GROUP: "rg-test-uat-001" #DestinationRG
  ARM_FACTORY_NAME: "adf-testproject-uat-001" #DestinationDF
  ARM_TEMPLATE_FILE: "./Azure-CICD-Test-adf_publish/adf-testproject-dev-001/ARMTemplateForFactory.json"
  ARM_PARAMETERS_FILE: "./Azure-CICD-Test-adf_publish/adf-testproject-dev-001/ARMTemplateParametersForFactory.json"

jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
    - name: checkout main branch
      uses: actions/checkout@v3
    - name: Checkout adf_publish branch
      uses: actions/checkout@v3
      
    - name: Install azure-cli
  # You may pin to the exact commit or the version.
  # uses: pietrobolcato/install-azure-cli-action@f01ae8ab9274a69a854ef40018c9686d60d4891e
      uses: pietrobolcato/install-azure-cli-action@v1

    - name: Login to Azure
      run: |
         az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
         az account set --subscription $ARM_SUBSCRIPTION_ID

    - name: data-factory-deploy
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        # Data Factory resource group name
        resourceGroupName: "$ARM_RESOURCE_GROUP"
        # Data factory name
        dataFactoryName: "$ARM_FACTORY_NAME"
        # ARM template file name
        armTemplateFile: "./Azure-CICD-Test-adf_publish/adf-testproject-dev-001/ARMTemplateForFactory.json"
        # ARM template parameters file name
        armTemplateParametersFile: "./Azure-CICD-Test-adf_publish/adf-testproject-dev-001/ARMTemplateParametersForFactory.json"
        # Parameters which will be replaced in the ARM template
        skipAzModuleInstallation: "false"