name: ADF_New4

on:
#   push:
#     branches:
#       - main

   workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_TEMPLATE_FILE: ".https://github.com/sandhyabhagam/Azure-CICD-Test/blob/c28fb8b9c1114ab9979b6ccb8fb5d5cb2d42849d/adf-testproject-dev-001/ARMTemplateForFactory.json"
  ARM_PARAMETERS_FILE: "https://github.com/sandhyabhagam/Azure-CICD-Test/blob/c28fb8b9c1114ab9979b6ccb8fb5d5cb2d42849d/adf-testproject-dev-001/ARMTemplateParametersForFactory.json"
  ARM_RESOURCE_GROUP: "rg-test-uat-001"
  ARM_FACTORY_NAME: "adf-testproject-uat-001"

jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: adf_publish
      
    - name: Install azure-cli
  # You may pin to the exact commit or the version.
  # uses: pietrobolcato/install-azure-cli-action@f01ae8ab9274a69a854ef40018c9686d60d4891e
      uses: pietrobolcato/install-azure-cli-action@v1

    - name: Login to Azure
      run: |
         az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
         az account set --subscription $ARM_SUBSCRIPTION_ID
    - name: Deploy ARM Templates
      run: |
        az account set --subscription "$ARM_SUBSCRIPTION_ID"
        az deployment group create --resource-group "$ARM_RESOURCE_GROUP" --template-file "$ARM_TEMPLATE_FILE" --parameters "@$ARM_PARAMETERS_FILE" --name "$ARM_FACTORY_NAME-deployment"
