name: ADF_NEW_2

on: 
  workflow_dispatch

inputs:
  resourceGroupName:
    description: 'rg-test-uat-001'
    required: true
  dataFactoryName:
    description: 'adf-testproject-uat-001'
    required: true
  armTemplateFile:
    description: 'ARMTemplateForFactory.json'
    required: false
    default: 'ARMTemplateForFactory.json'
  armTemplateParametersFile:
    description: 'ARMTemplateParametersForFactory.json'
    required: false
    default: 'ARMTemplateParametersForFactory.json'
  additionalParameters:
    description: 'Parameters which will be replaced in the ARM template'
    required: false
    default: ''

runs:
  using: 'composite'
    runs-on:  ubuntu-latest

    steps:
    - name: checkout main branch
      uses: actions/checkout@v3
    - name: Checkout adf_publish branch
      uses: actions/checkout@v3
    #- name: Read ARMTemplateForFactory.json
      #id: package
      #uses: juliangruber/read-file-action@v1
      #with:
        #path: ./adf-testproject-dev-001/ARMTemplateForFactory.json
      
    #steps:
      #- name: Checkout repository
        #uses: actions/checkout@v3
      #- name: Read package.json
        #id: package
        #uses: juliangruber/read-file-action@v1
        #with:
          #path: ./package.json
      #- name: Echo package.json
        #run: echo "${{ steps.package.outputs.content }}"
        #SourceWorkspaceName: "adf-testproject-dev-001" #SourceADF
        #ARM_TEMPLATE_FILE: "./adf-testproject-dev-001/ARMTemplateForFactory.json"
        #ARM_PARAMETERS_FILE: "./adf-testproject-dev-001/ARMTemplateParametersForFactory.json"
      
    - name: Install azure-cli
  # You may pin to the exact commit or the version.
  # uses: pietrobolcato/install-azure-cli-action@f01ae8ab9274a69a854ef40018c9686d60d4891e
      uses: pietrobolcato/install-azure-cli-action@v1

    - name: Login to Azure
      run: |
         az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
         az account set --subscription $ARM_SUBSCRIPTION_ID

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ${{ inputs.armTemplateFile }}
        parameters: ${{ inputs.armTemplateParametersFile }} factoryName=${{ inputs.dataFactoryName }} ${{ inputs.additionalParameters }}