name: ADF_New4

on:
#   push:
#     branches:
#       - main

   workflow_dispatch:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_RESOURCE_GROUP: 'rg-test-uat-001'
  ARM_FACTORY_NAME: 'adf-testproject-uat-001'
  SourceWorkspaceName: 'adf-testproject-dev-001'


jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
    - name: Checkout adf_publish branch
      uses: actions/checkout@v3
      with:
        ref: adf_publish
        # EITHER READ FILE HERE OR SAVE IT ON LOCAL RUNNER
      
    - name: Install azure-cli
  # You may pin to the exact commit or the version.
  # uses: pietrobolcato/install-azure-cli-action@f01ae8ab9274a69a854ef40018c9686d60d4891e
      uses: pietrobolcato/install-azure-cli-action@v1

    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.6
        az account set --subscription $ARM_SUBSCRIPTION_ID
        az deployment group create --resource-group $ARM_RESOURCE_GROUP --template-file ./${{ env.SourceWorkspaceName }}/TemplateForWorkspace.json --parameters ./${{ env.SourceWorkspaceName }}/TemplateParametersForWorkspace.json
